### ISSUE TITLE
Interaction Mappings import failure

### ISSUE THREAD

**Issue by fleming-scott** [SalesforceFoundation/Interactions-for-Student-Recruitment#10]
I'm installing into a fresh trial Org of Salesforce+HEDA.  I've followed the instructions as per the 'INTERACTIONS INSTALLATION AND CONFIGURATION GUIDE' but am having trouble importing the Interaction Mappings CSV. I've attached the CSV, and Request and Result summaries for the Data Loader for reference.

The error produced is:

CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY:INT_InteractionMapping:   execution of AfterInsert
caused by: System.NullPointerException: Attempt to   de-reference a null object
Trigger.INT_InteractionMapping: line 19, column   1:--
--

[result.txt](https://github.com/SalesforceFoundation/Interactions-for-Student-Recruitment/files/2102740/result.txt)
[request.txt](https://github.com/SalesforceFoundation/Interactions-for-Student-Recruitment/files/2102741/request.txt)

[Errors.xlsx](https://github.com/SalesforceFoundation/Interactions-for-Student-Recruitment/files/2102750/Errors.xlsx)

When entering the Interactions records manually there was an error produced when creating the Interaction__c.Middle_Name__c  ->  Contact.MiddleName record because the Contact.MiddleName field did not exist.

**Comment by karamcintyre** [comment]
This is because Middle Name is a standard field that has to be enabled in the User Interface settings. The Installation and Configuration Guide (page 33) has been updated to link to a Knowledge Article on how to do that.
